version: "3.3"

services:
  nuxt:
    build:
      context: .
    image: nuxt_build
    container_name: nuxt_build
    command: npm run startProduction
    ports:
      - "3000:3000"
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./certs/:/etc/certs
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5000:8080"
    volumes:
      - ./swagger-gen:/foo
    environment:
      - SWAGGER_JSON=/foo/.swagger.json
      - BASE_URL=/docs
    command:
