version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_build
    container_name: nuxt_build
    command: npm run startProduction
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"