// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "auth-only-service.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthOnlyService } from "./auth-only-service";
import type { BedList } from "./common-messages";
import type { ModifyBedRequest } from "./auth-only-service";
import type { BedMutableInfo } from "./common-messages";
import type { BedId } from "./common-messages";
import type { ReviewRequest } from "./auth-only-service";
import type { GetBookingsResponse } from "./auth-only-service";
import type { BookResponse } from "./auth-only-service";
import type { Booking } from "./common-messages";
import type { ProfilePic } from "./common-messages";
import type { VerifyMailResponse } from "./auth-only-service";
import type { VerifyMailRequest } from "./auth-only-service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Empty } from "./common-messages";
import type { AccountInfo } from "./common-messages";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service AuthOnlyService
 */
export interface IAuthOnlyServiceClient {
    /**
     * Called only if the account does not exist
     *
     * @generated from protobuf rpc: SignUp(AccountInfo) returns (Empty);
     */
    signUp(input: AccountInfo, options?: RpcOptions): UnaryCall<AccountInfo, Empty>;
    /**
     * @generated from protobuf rpc: VerifyMail(VerifyMailRequest) returns (VerifyMailResponse);
     */
    verifyMail(input: VerifyMailRequest, options?: RpcOptions): UnaryCall<VerifyMailRequest, VerifyMailResponse>;
    /**
     * @generated from protobuf rpc: GetAccountInfo(Empty) returns (AccountInfo);
     */
    getAccountInfo(input: Empty, options?: RpcOptions): UnaryCall<Empty, AccountInfo>;
    /**
     * @generated from protobuf rpc: GetProfilePic(Empty) returns (ProfilePic);
     */
    getProfilePic(input: Empty, options?: RpcOptions): UnaryCall<Empty, ProfilePic>;
    /**
     * @generated from protobuf rpc: SetProfilePic(ProfilePic) returns (Empty);
     */
    setProfilePic(input: ProfilePic, options?: RpcOptions): UnaryCall<ProfilePic, Empty>;
    /**
     * It also delete all his beds and booking availabilities, review to other's beds, and
     *
     * @generated from protobuf rpc: DeleteAccount(Empty) returns (Empty);
     */
    deleteAccount(input: Empty, options?: RpcOptions): UnaryCall<Empty, Empty>;
    /**
     * If the mail is changed, is needed to verify the account (and the eventual old verification code becomed invalid), you can call this function even if
     * the account is not verified, because for example the mail was wrong.
     *
     * @generated from protobuf rpc: UpdateAccountInfo(AccountInfo) returns (Empty);
     */
    updateAccountInfo(input: AccountInfo, options?: RpcOptions): UnaryCall<AccountInfo, Empty>;
    /**
     * FOR EVERY FOLLOWING RPC IS ASSUMED THAT THE CALLER HAS A VERIFIED ACCOUNT
     * GUEST RPCs
     * "Human proof token" are then sent through mail to both guest, and host
     *
     * The book is available
     *
     * @generated from protobuf rpc: Book(Booking) returns (BookResponse);
     */
    book(input: Booking, options?: RpcOptions): UnaryCall<Booking, BookResponse>;
    /**
     * @generated from protobuf rpc: GetMyBookings(Empty) returns (GetBookingsResponse);
     */
    getMyBookings(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetBookingsResponse>;
    /**
     * Is assumed that A user can review only a past booking that has no review from the user
     *
     * @generated from protobuf rpc: Review(ReviewRequest) returns (Empty);
     */
    review(input: ReviewRequest, options?: RpcOptions): UnaryCall<ReviewRequest, Empty>;
    /**
     * Is assumed that A user can review only a past booking that has no review from the user
     *
     * @generated from protobuf rpc: RemoveReview(BedId) returns (Empty);
     */
    removeReview(input: BedId, options?: RpcOptions): UnaryCall<BedId, Empty>;
    /**
     * HOST RPCs
     *
     * @generated from protobuf rpc: AddBed(BedMutableInfo) returns (Empty);
     */
    addBed(input: BedMutableInfo, options?: RpcOptions): UnaryCall<BedMutableInfo, Empty>;
    /**
     * @generated from protobuf rpc: ModifyMyBed(ModifyBedRequest) returns (Empty);
     */
    modifyMyBed(input: ModifyBedRequest, options?: RpcOptions): UnaryCall<ModifyBedRequest, Empty>;
    /**
     * @generated from protobuf rpc: RemoveMyBed(BedId) returns (Empty);
     */
    removeMyBed(input: BedId, options?: RpcOptions): UnaryCall<BedId, Empty>;
    /**
     * @generated from protobuf rpc: GetMyBeds(Empty) returns (BedList);
     */
    getMyBeds(input: Empty, options?: RpcOptions): UnaryCall<Empty, BedList>;
    /**
     * @generated from protobuf rpc: AddBookingAvaiability(Booking) returns (Empty);
     */
    addBookingAvaiability(input: Booking, options?: RpcOptions): UnaryCall<Booking, Empty>;
    /**
     * @generated from protobuf rpc: RemoveBookAvaiability(Booking) returns (Empty);
     */
    removeBookAvaiability(input: Booking, options?: RpcOptions): UnaryCall<Booking, Empty>;
}
/**
 * @generated from protobuf service AuthOnlyService
 */
export class AuthOnlyServiceClient implements IAuthOnlyServiceClient, ServiceInfo {
    typeName = AuthOnlyService.typeName;
    methods = AuthOnlyService.methods;
    options = AuthOnlyService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Called only if the account does not exist
     *
     * @generated from protobuf rpc: SignUp(AccountInfo) returns (Empty);
     */
    signUp(input: AccountInfo, options?: RpcOptions): UnaryCall<AccountInfo, Empty> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AccountInfo, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyMail(VerifyMailRequest) returns (VerifyMailResponse);
     */
    verifyMail(input: VerifyMailRequest, options?: RpcOptions): UnaryCall<VerifyMailRequest, VerifyMailResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyMailRequest, VerifyMailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAccountInfo(Empty) returns (AccountInfo);
     */
    getAccountInfo(input: Empty, options?: RpcOptions): UnaryCall<Empty, AccountInfo> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AccountInfo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProfilePic(Empty) returns (ProfilePic);
     */
    getProfilePic(input: Empty, options?: RpcOptions): UnaryCall<Empty, ProfilePic> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ProfilePic>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetProfilePic(ProfilePic) returns (Empty);
     */
    setProfilePic(input: ProfilePic, options?: RpcOptions): UnaryCall<ProfilePic, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProfilePic, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * It also delete all his beds and booking availabilities, review to other's beds, and
     *
     * @generated from protobuf rpc: DeleteAccount(Empty) returns (Empty);
     */
    deleteAccount(input: Empty, options?: RpcOptions): UnaryCall<Empty, Empty> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * If the mail is changed, is needed to verify the account (and the eventual old verification code becomed invalid), you can call this function even if
     * the account is not verified, because for example the mail was wrong.
     *
     * @generated from protobuf rpc: UpdateAccountInfo(AccountInfo) returns (Empty);
     */
    updateAccountInfo(input: AccountInfo, options?: RpcOptions): UnaryCall<AccountInfo, Empty> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<AccountInfo, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * FOR EVERY FOLLOWING RPC IS ASSUMED THAT THE CALLER HAS A VERIFIED ACCOUNT
     * GUEST RPCs
     * "Human proof token" are then sent through mail to both guest, and host
     *
     * The book is available
     *
     * @generated from protobuf rpc: Book(Booking) returns (BookResponse);
     */
    book(input: Booking, options?: RpcOptions): UnaryCall<Booking, BookResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<Booking, BookResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyBookings(Empty) returns (GetBookingsResponse);
     */
    getMyBookings(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetBookingsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetBookingsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Is assumed that A user can review only a past booking that has no review from the user
     *
     * @generated from protobuf rpc: Review(ReviewRequest) returns (Empty);
     */
    review(input: ReviewRequest, options?: RpcOptions): UnaryCall<ReviewRequest, Empty> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReviewRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Is assumed that A user can review only a past booking that has no review from the user
     *
     * @generated from protobuf rpc: RemoveReview(BedId) returns (Empty);
     */
    removeReview(input: BedId, options?: RpcOptions): UnaryCall<BedId, Empty> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<BedId, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * HOST RPCs
     *
     * @generated from protobuf rpc: AddBed(BedMutableInfo) returns (Empty);
     */
    addBed(input: BedMutableInfo, options?: RpcOptions): UnaryCall<BedMutableInfo, Empty> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<BedMutableInfo, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ModifyMyBed(ModifyBedRequest) returns (Empty);
     */
    modifyMyBed(input: ModifyBedRequest, options?: RpcOptions): UnaryCall<ModifyBedRequest, Empty> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ModifyBedRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveMyBed(BedId) returns (Empty);
     */
    removeMyBed(input: BedId, options?: RpcOptions): UnaryCall<BedId, Empty> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<BedId, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyBeds(Empty) returns (BedList);
     */
    getMyBeds(input: Empty, options?: RpcOptions): UnaryCall<Empty, BedList> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, BedList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddBookingAvaiability(Booking) returns (Empty);
     */
    addBookingAvaiability(input: Booking, options?: RpcOptions): UnaryCall<Booking, Empty> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<Booking, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveBookAvaiability(Booking) returns (Empty);
     */
    removeBookAvaiability(input: Booking, options?: RpcOptions): UnaryCall<Booking, Empty> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<Booking, Empty>("unary", this._transport, method, opt, input);
    }
}
